{% set name = "palantir-oauth-client" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/palantir-oauth-client-{{ version }}.tar.gz
  sha256: ac44c94a417a90dae0cfdea0780dfe128ce38a8a1efa9b6fdbe3a223e397905a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - setuptools >=35.0.2
    - setuptools-scm
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - oauthlib >=3.2.2
    - requests >=2.28.2
    - requests-oauthlib >=1.3.1
    - typing >=3.7.4
    - urllib3 >=1.26.14

test:
  imports:
    - palantir_oauth_client

about:
  home: https://github.com/palantir/palantir-oauth-client
  summary: OAuth2 client for Palantir Foundry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ahggns
    - tom-s-powell
    - AlexandreGuinaudeau
    - talDias
